config/routes.rb
Rails.application.routes.draw do

  resources :tracks, only: [:create, :destroy, :update]
  devise_for :users
  root to: "pages#index"
  get '/profile', to: 'pages#profile'

end

app/models/tag.rb
class Tag < ActiveRecord::Base
    has_many :tags_tracks
    has_many :tracks, through: :tags_tracks
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :track
  belongs_to :tag
end

app/models/tags_track.rb
class TagsTrack < ActiveRecord::Base
    belongs_to :track
    belongs_to :tag
end

app/models/track.rb
class Track < ActiveRecord::Base
    belongs_to :user
    has_many :tags_tracks
    has_many :tags, through: :tags_tracks
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable

         has_many :tracks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  unless Rails.env.development?
    protect_from_forgery with: :exception
  end

  # before_filter :current_user, :cors_preflight_check
  # after_filter :cors_set_access_control_headers

  #   # For all responses in this controller, return the CORS access control headers.

  #   def cors_set_access_control_headers
  #     headers['Access-Control-Allow-Origin'] = '*'
  #     headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
  #     headers['Access-Control-Allow-Headers'] = '*'
  #     headers['Access-Control-Max-Age'] = "1728000"
  #   end

  #   # If this is a preflight OPTIONS request, then short-circuit the
  #   # request, return only the necessary headers and return an empty
  #   # text/plain.

  #   def cors_preflight_check
  #     if request.method == :options
  #       headers['Access-Control-Allow-Origin'] = '*'
  #       headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
  #       headers['Access-Control-Allow-Headers'] = '*'
  #       headers['Access-Control-Max-Age'] = '1728000'
  #       render :text => '', :content_type => 'text/plain'
  #     end
  #   end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    before_action :authenticate_user!, only: [:profile, :tracks]

    def index
        unless user_signed_in?
            render 'pages/cover'
        else
            @tracks = Track.where(user_id: current_user).order('id DESC')
            render 'pages/tracks'
        end
        #render 'pages/index' lo hace por defecto
    end


    def profile
        @user = current_user
        render 'pages/profile'
    end


    def tracks
    end
end




#redirect -> url completa (por definicion del protocol http)
#link_to -> path

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
    #before_action :authenticate_user!
    #skip_before_action :verify_authenticity_token, only: [:create]
    # extension stopped working, had to remove authentication check and hard-code user_id = 1 in create, update
    def create
        params['track'][:user_id] = 1
        @track = Track.new(track_params)
          if @track.save
            params[:tags].each do |tag|
            @track.tags << Tag.find_or_create_by(name: tag)
            # Tag.new(tag_params)

            end
            render json: @track.to_json

          else
            format.html { render :index }
          end
        end

    def destroy
        @track = Track.find(params[:id])
        @track.destroy
        respond_to do |format|
            format.html { redirect_to :back, notice: 'Track destroyed.' }
        end
    end

    def update

      params['track'][:user_id] = 1
      @track = Track.find(params[:id])
      respond_to do |format|
        if @track.update(track_params)
          format.html { redirect_to root_path, notice: 'Track updated.' }
        else
          format.html { render :index }
        end
      end
    end

    def track_params
      params.require(:track).permit(:artist, :title, :url, :user_id)
    end

    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicSave</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" href="favicon.ico">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p id="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

<div class="container">
  <div class="col-md-4 col-md-offset-4">
    <p><small>A project for <a href="http://ironhack.com">Ironhack</a>, by <a href="https://es.linkedin.com/in/jesusgarciamar">Jesús García</a>.</small>
    </p>
  </div>
</div>

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</body>
</html>

app/views/pages/cover.html.erb
<div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container">

          <div class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand">Cover</h3>
              <nav>
                <ul class="nav masthead-nav">
                  <li class="active"><a href="#">Home</a></li>
                  <li><a href="#">Features</a></li>
                  <li><a href="#">Contact</a></li>
                </ul>
              </nav>
            </div>
          </div>

          <div class="inner cover">
            <h1 class="cover-heading"></h1>
            <p class="lead">Save the music you find online.</p>
            <p class="lead">
              <a href="/users/sign_up" class="btn btn-lg btn-default">Sign up</a>
            </p>
            <p class="lead">
              <a href="/users/sign_in" class="btn btn-lg btn-default">Sign in</a>
            </p>
            <p class="lead">
              <a href="#" class="btn btn-lg btn-default">MusicSave for Chrome</a>
            </p>
          </div>

          <!-- <div class="mastfoot">
            <div class="inner">
              <p>A project for<a href="http://ironhack.com">Ironhack</a>, by <a href="https://es.linkedin.com/in/jesusgarciamar">Jesús García</a>.</p>
            </div>
          </div> -->

        </div>

      </div>

</div>

app/views/pages/index.html.erb
<%= link_to "Log in", new_user_session_path %>

<%= link_to "Sign up", new_user_registration_path %>

app/views/pages/profile.html.erb
<h2><%= current_user.id %></h2>

<p>
<strong>Email:</strong> <%= current_user.email %>
</p>

app/views/pages/search_results.html.erb
<div>

</div>

app/views/pages/tracks.html.erb
<!-- video, profile/signout -->

<div class="container-fluid">
  <div class="row">
    <div class="col-md-3 col-md-offset-4 video-container">
      <iframe width="560" height="310" src="https://www.youtube.com/embed/" frameborder="0" allowfullscreen></iframe>
    </div>
    <div class="col-md-12 col-md-offset-11">
      <div class="btn-group-vertical">
          <%= link_to 'Profile', profile_path, class: "btn btn-default btn-sm" %>
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "btn btn-default btn-sm" %>
      </div>
    </div>
  </div>
</div>

<hr>

<!-- sidebar and tracks table -->

<div class="container-fluid">
  <div class="row">
    <div class="col-md-2">

      <!-- search form -->

      <form class="form-group" id="search-form">
        <label class="control-label">Search Youtube</label>
        <div class="input-group">
          <input type="text" class="form-control" id="search-contents">
          <span class="input-group-btn">
            <button class="btn btn-default" type="submit">Search</button>
          </span>
        </div>
      </form>

      <!-- new track -->

      <div id="new-track-button">
        <%= link_to 'New Track',  tracks_path, class: "btn btn-default btn-xs pagination-centered" %>
      </div>

      <!-- Tags -->

      <div>
        <a class="btn btn-default btn-lg btn-block" id="tags-button">Tags</a>
      </div>

      <div class="row hidden" id="tags">
        <div class="col-md-4">
          <ul>
            <li>
              <!-- Initial Tags (OR) -->
            </li>
          </ul>
        </div>
        <div class="col-md-4 left-border-outline">
          <ul>
            <li>
              <!-- Additional Tags (AND) -->
            </li>
          </ul>
        </div>
        <div class="col-md-4 left-border-outline">
          <ul>
            <li>
              <!-- Excluded Tags (NOT) -->
            </li>
          </ul>
        </div>
      </div>

      <!-- Playlists -->

      <div>
        <a class="btn btn-default btn-lg btn-block" id="playlists-button">Playlists</a>
      </div>

      <div class="row hidden" id="playlists">
        Playlists
      </div>
    </div>

    <!-- tracks table -->

    <div class="col-md-9 left-border-outline">

      <table class="table table-striped table-hover" id="tracks-table">
        <thead>
          <tr>
            <th>Artist</th>
            <th>Title</th>
            <th colspan="4"></th>
          </tr>
        </thead>
        <tbody>
          <% @tracks.each do |track| %>
            <tr data-id="<%= track.id %>">
              <td class="artist"><%= track.artist %></td>
              <td class="title"><%= track.title %></td>
              <td>
                <!-- <a target="_blank" href="<%= track.url %>"> -->
                  <button type="button" class="btn btn-default btn-xs play" value="<%= track.url %>">
                    <span class="glyphicon glyphicon-play" aria-hidden="true"></span>
                  </button>
                <!-- </a> -->
              </td>
              <td>
                <div class="btn-group">
                  <a href="javascript:void(0)" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    <strong>. . .</strong>
                    <!-- <span class="glyphicon glyphicon-option-horizontal" aria-hidden="true"></span> -->
                  </a>
                  <ul class="dropdown-menu dropdown-menu-right">
                    <li><a href="javascript:void(0)" class="add-tags-button">Add tags</a></li>
                    <li><a href="javascript:void(0)" class="add-tags-button">Edit track</a></li>
                    <li><%= link_to 'Delete track', track, method: :delete, remote: true, data: { confirm: 'Are you sure?' } %></li>
                  </ul>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<hr>

<!-- update form -->

<div class="row" id="update-form">
  <form class="form-inline">
    <input name="_method" type="hidden" value="patch" />
    <input value="1" type="hidden" id="track-id"/>
    <div class="form-group">
      <label for="artist">Artist</label>
      <input type="text" class="form-control input-sm" id="artist" placeholder="Artist">
    </div>
    <div class="form-group">
      <label for="title">Title</label>
      <input type="email" class="form-control input-sm" id="title" placeholder="Title">
    </div>
    <div class="form-group">
      <label for="url">Youtube link</label>
      <input type="email" class="form-control input-sm" id="url" placeholder="Youtube link">
    </div>
    <button type="submit" class="btn btn-default btn-xs"> Update Track </button>
  </form>
</div>

<!-- add tags form -->

<!-- <td> -->
<form class="form-inline" id="add-tags-form">
  <div class="form-group">
    <label for="tags-input">Add tags</label>
    <input type="text" class="form-control input-sm" id="tags-input" placeholder="tag, tag, ...">
  </div>
  <div class="typed-tags">
  </div>
  <button type="submit" class="btn btn-primary btn-xs">Add</button>
</form>
<!-- </td> -->

<!-- modal -->

<div class="modal fade js-modal">
  <div class="modal-dialog">
    <div class="modal-content">

      <div class="modal-header">
        <!-- Close button -->
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span>&times;</span>
        </button>
        <h3>Header</h3>
      </div>

      <div class="modal-body">
          <div class="container" id="results"></div>
      </div>

    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->